/**
 * Auto-generated TypeScript tokens
 * DO NOT EDIT MANUALLY
 */

export const primitiveOther = {
  'type-font-family-default': 'Inter',
  'type-font-family-mono': 'Fira Code',
  'fade': {"type":"linear","angle":90,"stops":[{"color":"#fefeff00","position":0},{"color":"{System.Surface.Background}","position":0.55}]},
  'fade2': {"type":"linear","angle":90,"stops":[{"color":"#12121300","position":0},{"color":"{System.Surface.Background}","position":0.55}]},
  'heading-h1-hero-headline': {"fontFamily":"Inter","fontSize":"56px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'heading-h2-page-heading': {"fontFamily":"Inter","fontSize":"32px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'heading-h3-section-heading': {"fontFamily":"Inter","fontSize":"24px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'heading-h4-subsection-heading': {"fontFamily":"Inter","fontSize":"18px","fontWeight":600,"letterSpacing":"0px","lineHeight":"130%","textTransform":"none","textDecoration":"none"},
  'heading-h5-small-title': {"fontFamily":"Inter","fontSize":"14px","fontWeight":600,"letterSpacing":"0px","lineHeight":"110%","textTransform":"none","textDecoration":"none"},
  'heading-h6-tagline': {"fontFamily":"Inter","fontSize":"12px","fontWeight":600,"letterSpacing":"0px","lineHeight":"130%","textTransform":"none","textDecoration":"none"},
  'body-l-regular': {"fontFamily":"Inter","fontSize":"18px","fontWeight":400,"letterSpacing":"0px","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-l-strong': {"fontFamily":"Inter","fontSize":"18px","fontWeight":500,"letterSpacing":"0%","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-m-regular': {"fontFamily":"Inter","fontSize":"16px","fontWeight":400,"letterSpacing":"0px","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-m-strong': {"fontFamily":"Inter","fontSize":"16px","fontWeight":500,"letterSpacing":"0%","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-s-regular': {"fontFamily":"Inter","fontSize":"14px","fontWeight":400,"letterSpacing":"0%","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-s-strong': {"fontFamily":"Inter","fontSize":"14px","fontWeight":600,"letterSpacing":"0%","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-xs-regular': {"fontFamily":"Inter","fontSize":"12px","fontWeight":400,"letterSpacing":"0%","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'body-xs-strong': {"fontFamily":"Inter","fontSize":"12px","fontWeight":500,"letterSpacing":"0%","lineHeight":"150%","textTransform":"none","textDecoration":"none"},
  'ui-label-m-regular': {"fontFamily":"Inter","fontSize":"16px","fontWeight":400,"letterSpacing":"0%","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'ui-label-m-strong': {"fontFamily":"Inter","fontSize":"16px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'ui-label-s-regular': {"fontFamily":"Inter","fontSize":"14px","fontWeight":400,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'ui-label-s-strong': {"fontFamily":"Inter","fontSize":"14px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'ui-label-xs-regular': {"fontFamily":"Inter","fontSize":"12px","fontWeight":400,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'ui-label-xs-strong': {"fontFamily":"Inter","fontSize":"12px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"none"},
  'uppercase-s': {"fontFamily":"Inter","fontSize":"13px","fontWeight":500,"letterSpacing":"0.75px","lineHeight":"130%","textTransform":"uppercase","textDecoration":"none"},
  'uppercase-xs': {"fontFamily":"Inter","fontSize":"11px","fontWeight":500,"letterSpacing":"0.5px","lineHeight":"130%","textTransform":"uppercase","textDecoration":"none"},
  'code-regular': {"fontFamily":"Fira Code","fontSize":"12px","fontWeight":400,"letterSpacing":"0px","lineHeight":"140%","textTransform":"none","textDecoration":"none"},
  'code-medium': {"fontFamily":"Fira Code","fontSize":"12px","fontWeight":500,"letterSpacing":"0px","lineHeight":"140%","textTransform":"none","textDecoration":"none"},
  'link-s': {"fontFamily":"Inter","fontSize":"12px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"underline"},
  'link-m': {"fontFamily":"Inter","fontSize":"14px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"underline"},
  'link-l': {"fontFamily":"Inter","fontSize":"16px","fontWeight":600,"letterSpacing":"0px","lineHeight":"120%","textTransform":"none","textDecoration":"underline"},
  'chat-heading1': {"fontFamily":"Inter","fontSize":"32px","fontWeight":600,"letterSpacing":"0px","lineHeight":"115%","textTransform":"none","textDecoration":"none"},
  'chat-heading2': {"fontFamily":"Inter","fontSize":"28px","fontWeight":600,"letterSpacing":"0px","lineHeight":"115%","textTransform":"none","textDecoration":"none"},
  'chat-heading3': {"fontFamily":"Inter","fontSize":"25px","fontWeight":600,"letterSpacing":"0px","lineHeight":"115%","textTransform":"none","textDecoration":"none"},
  'chat-heading4': {"fontFamily":"Inter","fontSize":"22px","fontWeight":600,"letterSpacing":"0px","lineHeight":"115%","textTransform":"none","textDecoration":"none"},
  'chat-heading5': {"fontFamily":"Inter","fontSize":"20px","fontWeight":600,"letterSpacing":"0px","lineHeight":"115%","textTransform":"none","textDecoration":"none"},
  'chat-heading6': {"fontFamily":"Inter","fontSize":"18px","fontWeight":600,"letterSpacing":"0px","lineHeight":"115%","textTransform":"none","textDecoration":"none"},
} as const;
