/**
 * Auto-generated TypeScript tokens
 * DO NOT EDIT MANUALLY
 */

export const semanticColors = {
  'system-primary-light': '#eaeaea',
  'system-primary-subtle': '#6d6d6e',
  'system-primary-default': '#121213',
  'system-primary-inverted': '#fefeff',
  'system-accent-lighter': '#e8f3ff',
  'system-accent-light': '#b4d3ff',
  'system-accent-subtle': '#4c96ff',
  'system-accent-default': '#0069ff',
  'system-accent-strong': '#002e6f',
  'system-content-heading': '#121213',
  'system-content-primary': '#29292a',
  'system-content-secondary': '#6d6d6e',
  'system-content-disabled': '#99999a',
  'system-content-inverted': '#fefeff',
  'system-content-accent': '#0069ff',
  'system-content-error': '#a8200d',
  'system-content-success': '#085d11',
  'system-content-warning': '#b18e0e',
  'system-content-on-inverted-heading': '#fefeff',
  'system-content-on-inverted-primary': '#f6f6f7',
  'system-content-on-inverted-secondary': '#99999a',
  'system-content-on-inverted-disabled': '#6d6d6e',
  'system-content-on-inverted-accent': '#4c96ff',
  'system-surface-background': '#fefeff',
  'system-surface-background-inverted': '#121213',
  'system-surface-background-inverted-alpha': '#121213d9',
  'system-surface-layer': '#f6f6f7',
  'system-surface-layer-strong': '#eaeaea',
  'system-surface-layer-stronger': '#cccccd',
  'system-surface-input': '#fefeff99',
  'system-surface-accent': '#0069ff',
  'system-surface-elevated': '#fefeff',
  'system-surface-elevated-inverted': '#121213',
  'system-stroke-default-alpha-subtle': '#1212131a',
  'system-stroke-default-alpha-medium': '#12121340',
  'system-stroke-default-alpha-strong': '#12121380',
  'system-stroke-ondark-alpha-subtle': '#fefeff33',
  'system-stroke-ondark-alpha-medium': '#fefeff66',
  'system-stroke-ondark-alpha-strong': '#fefeff99',
  'system-build-action': '#2dca8c',
  'system-build-data': '#7a59c2',
  'system-build-function': '#e4983b',
  'system-build-input': '#4b97ae',
  'system-build-workflow': '#eb5181',
  'system-icon-primary': '#29292a',
  'system-icon-secondary': '#6d6d6e',
  'system-icon-disabled': '#99999a',
  'system-icon-inverted': '#fefeff',
  'system-icon-accent-subtle': '#4c96ff',
  'system-icon-accent': '#0069ff',
  'system-icon-accent-strong': '#004bb7',
  'system-icon-error': '#a8200d',
  'system-icon-success': '#085d11',
  'system-icon-warning': '#b18e0e',
  'system-icon-on-inverted-primary': '#f6f6f7',
  'system-icon-on-inverted-secondary': '#99999a',
  'system-icon-on-inverted-disabled': '#6d6d6e',
  'system-icon-on-inverted-accent': '#4c96ff',
  'feedback-negative-light': '#fff3f1',
  'feedback-negative-default': '#cd4937',
  'feedback-negative-strong': '#a8200d',
  'feedback-warning-light': '#fff9e3',
  'feedback-warning-default': '#edc843',
  'feedback-warning-strong': '#b18e0e',
  'feedback-positive-light': '#f0fef1',
  'feedback-positive-default': '#34863c',
  'feedback-positive-strong': '#085d11',
} as const;
